# Node Tree Theme custom Configuration
## Docs:
## Source: https://github.com/Exisi/hexo-theme-node-tree

# Specify github user for header
github: Exisi

favicon: /favicon.ico

menu:
  tag:
    enable: true
  category:
    enable: true

sidebar:
  # Post title use title or filename, If not defined, default is false (filename).
  usePostTitle: false
  search:
    # If not defined, default is google. Set engines as
    # https://www.baidu.com/s?wd=
    # https://www.google.com/search?q=
    engine: https://www.google.com/search?q=

footer:
  copyright:
    # If `author` from Hexo `_config.yml` not defined, will be used.
    author:
      name: Exisi
      url: https://github.com/Exisi
    baseYear: 2022

comment:
  giscus:
    enable: false
    enableComment: true
    repo: Exisi/MagicBook
    repoid: R_kgDOIfu7zg
    reactions: 1

analysis:
  baidu:
    enable: false
    src: https://hm.baidu.com/hm.js?a678db57b009ca2bf262e45529b0d9eb
  google:
    enable: false
    src: https://www.googletagmanager.com/gtag/js?id=G-9T5T0HZ66R
    config: G-9T5T0HZ66R

statistics:
  busuanzi:
    # Specify to open busuanzi statistics
    enable: true