title: node-tree

author: Exisi

links:
  github: https://github.com/Exisi
  
favicon: /favicon.ico

#giscus
giscus:
    # 评论
    enableComment: true
    # Discussion 项目地址
    repo: Exisi/Exisi
    # Discussion 项目
    repoid: MDEwOlJlcG9zaXRvcnkzODU0OTA3MTA=
    # 反应
    reactions: 1

# valine
valine:
    # 评论
    enableComment: false
    # 阅读量
    enableCounter: false
    # valine appID
    appID:
    # valine appKey
    appKey:
    placeholder: 请输入评论
    avatar: retro

# 是否开启“不蒜子”统计访问量
busuanzi: true

# 底部版权开始年份
siteStartYear: 2022

####### 站外搜索配置 #####
# 站点如果【被搜索引擎收录】，可以配置通过搜索引擎全站搜索
# searchEngine：搜索引擎，不配置则默认为谷歌，可替换为百度等其他搜索引擎的搜索 URL
#   https://www.baidu.com/s?wd=
#   https://www.google.com/search?q=
# homeHost：要搜索的站点域名，不配置默认取当前页面的域名
searchEngine: https://www.google.com/search?q=
homeHost: m.exi.ink

tags: true
categories: true

# 左侧导航栏，用文件名还是文章名
sidebar:
  # usePostTitle 为 ture 用文章名，不填或为 false 用文件名
  usePostTitle: false