# Node Tree Theme Configuration
## Source: https://github.com/Exisi/hexo-theme-node-tree

favicon: /favicon.ico

# Specify github user for header（username）
github: Exisi

menu:
  tag:
    enable: true
  category:
    enable: true

sidebar:
  # Post title use title or filename, If not defined, default is false (filename).
  usePostTitle: false
  search:
    # If not defined, default is google. Set engines as
    # https://www.baidu.com/s?wd=
    # https://www.google.com/search?q=
    engine: https://www.google.com/search?q=

footer:
  copyright:
    # If `author` from Hexo `_config.yml` not defined, will be used.
    author:
      name: Exisi
      url:
    baseYear: 2024

comment:
  giscus:
    enable: false
    enableComment: true
    repo:
    repoid:
    reactions:

analysis:
  baidu:
    enable: false
    src:
  google:
    enable: false
    src:
    config:

statistics:
  busuanzi:
    # Specify to open busuanzi statistics
    enable: true